---
abstract: 'read/write from HTTP URIs as if they were filehandles'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: IO::Callback::HTTP
name: IO-Callback-HTTP
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Encode: 0
  HTTP::Request::Common: 0
  IO::Callback: 0
  LWP::UserAgent: 0
  URI: 0
  namespace::clean: 0
  perl: 5.8.8
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=IO-Callback-HTTP
  homepage: https://metacpan.org/release/IO-Callback-HTTP
  license: http://dev.perl.org/licenses/
version: 0.002
